### ISSUE TITLE
Create and configure firebase real-time database

### ISSUE THREAD

**Issue by fduquesne** [auchan-squid-game/auchan-squid-game#1]
### Description

Create a real-time database on [firebase](https://firebase.google.com/) (google service). The database schema must have this format :  
```JSON
{
  ToDetermine: ''
}
```

### Todo

- [x] Create a new firebase project
- [x] Create a new real-time database
- [x] Share the project to other contributers (get email address)
- [x] Generate data schema
