### ISSUE TITLE
Connect firebase with the application

### ISSUE THREAD

**Issue by fduquesne** [auchan-squid-game/auchan-squid-game#2]
### Description

Add firebase configuration on the application to use the firebase API. The node.js configuration is available once the real-time database is created.

### Todo

- [x] Add firebase configuration file in project sources (`./src/configs/firebase.js`)
- [x] create .env file
- [x] Test the connection to the database
- [x] Test to get mocked data
