### ISSUE TITLE
Manage the application signup

### ISSUE THREAD

**Issue by fduquesne** [auchan-squid-game/auchan-squid-game#3]
### Description

As a user, I want to be able to sign up to the application by giving my pseudonym (the id is equals to the success signup timestamp) and my password (this field will have to be confirmed).

### User interface

The user must have 3 fields : 
- Username
- Password
- Confirm password
A sublit button will check constraints, create a new user in database, auto connect the user and redirect into the homepage.

#### Constraints
- The 3 fields are mandatories
- The password field and the confirm password field must have the same value
- The username does not exist on database

### Todo

- [ ] Create a new view (SignupPage)
- [ ] Create a form
- [ ] Check constraints on submit
- [ ] Create new user on database
- [ ] Auto connect the user
- [ ] Redirect to the homepage
