### ISSUE TITLE
Manage the application signin

### ISSUE THREAD

**Issue by fduquesne** [auchan-squid-game/auchan-squid-game#4]
### Description

As a user, I want to be able to sign in to the application by giving my pseudonym and my password.

### User interface

The user must have 2 fields : 
- Username
- Password
A sublit button will check constraints, connect the user and redirect into the homepage.

#### Constraints
- The both fields are mandatories
- The username must exist on database
- The couple username/password must be appropriate

### Todo

- [x] Create a new view (SigninPage)
- [x] Create a form
- [x] Check constraints on submit
- [x] Connect the user
- [x] Redirect to the homepage
